[profile.default]
src = "src"
out = "out"
libraries = []
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./" }]

[fmt]
line_length = 120
number_underscore = "thousands"
tab_width = 4
bracket_spacing = true
int_types = "short"
quote_style = "double"

[profile.ci]
optimizer_runs = 999999

[profile.test]

[etherscan]
default = { key = "" }
